### ISSUE TITLE
java使用JDBC连接mysql数据库

### ISSUE THREAD

**Issue by joeyos** [joeyos/joeyos.github.io#1]
https://zhangquan1995.github.io/2018/04/29/java%E4%BD%BF%E7%94%A8JDBC%E8%BF%9E%E6%8E%A5mysql%E6%95%B0%E6%8D%AE%E5%BA%93/#comments

**Comment by zhangquan1995** [comment]
test comments of gitment...

**Comment by zhangquan1995** [comment]
test comments...
## h1

### h2

https://www.baidu.com
